# {
#     "location": {
#         "name": "Folsom",
#         "region": "California",
#         "country": "United States of America",
#         "lat": 38.6781,
#         "lon": -121.175,
#         "tz_id": "America/Los_Angeles",
#         "localtime_epoch": 1757118185,
#         "localtime": "2025-09-05 17:23",
#     },
#     "current": {
#         "last_updated_epoch": 1757117700,
#         "last_updated": "2025-09-05 17:15",
#         "temp_c": 30.2,
#         "temp_f": 86.4,
#         "is_day": 1,
#         "condition": {
#             "text": "Sunny",
#             "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
#             "code": 1000,
#         },
#         "wind_mph": 6.9,
#         "wind_kph": 11.2,
#         "wind_degree": 215,
#         "wind_dir": "SW",
#         "pressure_mb": 1008.0,
#         "pressure_in": 29.76,
#         "precip_mm": 0.0,
#         "precip_in": 0.0,
#         "humidity": 33,
#         "cloud": 0,
#         "feelslike_c": 29.2,
#         "feelslike_f": 84.5,
#         "windchill_c": 32.3,
#         "windchill_f": 90.2,
#         "heatindex_c": 32.0,
#         "heatindex_f": 89.7,
#         "dewpoint_c": 13.8,
#         "dewpoint_f": 56.8,
#         "vis_km": 16.0,
#         "vis_miles": 9.0,
#         "uv": 1.7,
#         "gust_mph": 8.0,
#         "gust_kph": 12.9,
#         "short_rad": 749.73,
#         "diff_rad": 110.95,
#         "dni": 0.0,
#         "gti": 115.23,
#     },
#     "forecast": {
#         "forecastday": [
#             {
#                 "date": "2025-09-05",
#                 "date_epoch": 1757030400,
#                 "day": {
#                     "maxtemp_c": 34.0,
#                     "maxtemp_f": 93.2,
#                     "mintemp_c": 15.8,
#                     "mintemp_f": 60.4,
#                     "avgtemp_c": 23.2,
#                     "avgtemp_f": 73.7,
#                     "maxwind_mph": 8.3,
#                     "maxwind_kph": 13.3,
#                     "totalprecip_mm": 0.0,
#                     "totalprecip_in": 0.0,
#                     "totalsnow_cm": 0.0,
#                     "avgvis_km": 10.0,
#                     "avgvis_miles": 6.0,
#                     "avghumidity": 60,
#                     "daily_will_it_rain": 0,
#                     "daily_chance_of_rain": 0,
#                     "daily_will_it_snow": 0,
#                     "daily_chance_of_snow": 0,
#                     "condition": {
#                         "text": "Sunny",
#                         "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
#                         "code": 1000,
#                     },
#                     "uv": 1.8,
#                 },
#                 "astro": {
#                     "sunrise": "06:38 AM",
#                     "sunset": "07:28 PM",
#                     "moonrise": "06:38 PM",
#                     "moonset": "04:06 AM",
#                     "moon_phase": "Waxing Gibbous",
#                     "moon_illumination": 91,
#                     "is_moon_up": 1,
#                     "is_sun_up": 0,
#                 },
#                 "hour": [
#                     {
#                         "time_epoch": 1757055600,
#                         "time": "2025-09-05 00:00",
#                         "temp_c": 20.9,
#                         "temp_f": 69.7,
#                         "is_day": 0,
#                         "condition": {
#                             "text": "Clear ",
#                             "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
#                             "code": 1000,
#                         },
#                         "wind_mph": 5.6,
#                         "wind_kph": 9.0,
#                         "wind_degree": 151,
#                         "wind_dir": "SSE",
#                         "pressure_mb": 1010.0,
#                         "pressure_in": 29.82,
#                         "precip_mm": 0.0,
#                         "precip_in": 0.0,
#                         "snow_cm": 0.0,
#                         "humidity": 63,
#                         "cloud": 9,
#                         "feelslike_c": 20.9,
#                         "feelslike_f": 69.7,
#                         "windchill_c": 20.9,
#                         "windchill_f": 69.7,
#                         "heatindex_c": 21.3,
#                         "heatindex_f": 70.3,
#                         "dewpoint_c": 13.3,
#                         "dewpoint_f": 55.9,
#                         "will_it_rain": 0,
#                         "chance_of_rain": 0,
#                         "will_it_snow": 0,
#                         "chance_of_snow": 0,
#                         "vis_km": 10.0,
#                         "vis_miles": 6.0,
#                         "gust_mph": 10.0,
#                         "gust_kph": 16.0,
#                         "uv": 0,
#                         "short_rad": 0,
#                         "diff_rad": 0,
#                         "dni": 0,
#                         "gti": 0,
#                     },
#                     {
#                         "time_epoch": 1757059200,
#                         "time": "2025-09-05 01:00",
#                         "temp_c": 18.8,
#                         "temp_f": 65.9,
#                         "is_day": 0,
#                         "condition": {
#                             "text": "Clear ",
#                             "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
#                             "code": 1000,
#                         },
#                         "wind_mph": 4.9,
#                         "wind_kph": 7.9,
#                         "wind_degree": 147,
#                         "wind_dir": "SSE",
#                         "pressure_mb": 1010.0,
#                         "pressure_in": 29.81,
#                         "precip_mm": 0.0,
#                         "precip_in": 0.0,
#                         "snow_cm": 0.0,
#                         "humidity": 68,
#                         "cloud": 4,
#                         "feelslike_c": 18.8,
#                         "feelslike_f": 65.9,
#                         "windchill_c": 18.8,
#                         "windchill_f": 65.9,
#                         "heatindex_c": 19.0,
#                         "heatindex_f": 66.2,
#                         "dewpoint_c": 13.3,
#                         "dewpoint_f": 56.0,
#                         "will_it_rain": 0,
#                         "chance_of_rain": 0,
#                         "will_it_snow": 0,
#                         "chance_of_snow": 0,
#                         "vis_km": 10.0,
#                         "vis_miles": 6.0,
#                         "gust_mph": 9.0,
#                         "gust_kph": 14.5,
#                         "uv": 0,
#                         "short_rad": 0,
#                         "diff_rad": 0,
#                         "dni": 0,
#                         "gti": 0,
#                     },
#                     {
#                         "time_epoch": 1757062800,
#                         "time": "2025-09-05 02:00",
#                         "temp_c": 17.6,
#                         "temp_f": 63.7,
#                         "is_day": 0,
#                         "condition": {
#                             "text": "Partly Cloudy ",
#                             "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
#                             "code": 1003,
#                         },
#                         "wind_mph": 4.7,
#                         "wind_kph": 7.6,
#                         "wind_degree": 153,
#                         "wind_dir": "SSE",
#                         "pressure_mb": 1010.0,
#                         "pressure_in": 29.84,
#                         "precip_mm": 0.0,
#                         "precip_in": 0.0,
#                         "snow_cm": 0.0,
#                         "humidity": 81,
#                         "cloud": 39,
#                         "feelslike_c": 17.6,
#                         "feelslike_f": 63.7,
#                         "windchill_c": 17.6,
#                         "windchill_f": 63.7,
#                         "heatindex_c": 17.7,
#                         "heatindex_f": 63.9,
#                         "dewpoint_c": 13.5,
#                         "dewpoint_f": 56.2,
#                         "will_it_rain": 0,
#                         "chance_of_rain": 0,
#                         "will_it_snow": 0,
#                         "chance_of_snow": 0,
#                         "vis_km": 10.0,
#                         "vis_miles": 6.0,
#                         "gust_mph": 9.0,
#                         "gust_kph": 14.4,
#                         "uv": 0,
#                         "short_rad": 0,
#                         "diff_rad": 0,
#                         "dni": 0,
#                         "gti": 0,
#                     },
#                     {
#                         "time_epoch": 1757066400,
#                         "time": "2025-09-05 03:00",
#                         "temp_c": 16.9,
#                         "temp_f": 62.4,
#                         "is_day": 0,
#                         "condition": {
#                             "text": "Partly Cloudy ",
#                             "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
#                             "code": 1003,
#                         },
#                         "wind_mph": 4.7,
#                         "wind_kph": 7.6,
#                         "wind_degree": 154,
#                         "wind_dir": "SSE",
#                         "pressure_mb": 1010.0,
#                         "pressure_in": 29.84,
#                         "precip_mm": 0.0,
#                         "precip_in": 0.0,
#                         "snow_cm": 0.0,
#                         "humidity": 84,
#                         "cloud": 42,
#                         "feelslike_c": 16.9,
#                         "feelslike_f": 62.4,
#                         "windchill_c": 16.9,
#                         "windchill_f": 62.4,
#                         "heatindex_c": 16.9,
#                         "heatindex_f": 62.5,
#                         "dewpoint_c": 13.8,
#                         "dewpoint_f": 56.8,
#                         "will_it_rain": 0,
#                         "chance_of_rain": 0,
#                         "will_it_snow": 0,
#                         "chance_of_snow": 0,
#                         "vis_km": 10.0,
#                         "vis_miles": 6.0,
#                         "gust_mph": 8.8,
#                         "gust_kph": 14.2,
#                         "uv": 0,
#                         "short_rad": 0,
#                         "diff_rad": 0,
#                         "dni": 0,
#                         "gti": 0,
#                     },
#                     {
#                         "time_epoch": 1757070000,
#                         "time": "2025-09-05 04:00",
#                         "temp_c": 16.5,
#                         "temp_f": 61.6,
#                         "is_day": 0,
#                         "condition": {
#                             "text": "Partly Cloudy ",
#                             "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
#                             "code": 1003,
#                         },
#                         "wind_mph": 4.5,
#                         "wind_kph": 7.2,
#                         "wind_degree": 159,
#                         "wind_dir": "SSE",
#                         "pressure_mb": 1010.0,
#                         "pressure_in": 29.83,
#                         "precip_mm": 0.0,
#                         "precip_in": 0.0,
#                         "snow_cm": 0.0,
#                         "humidity": 86,
#                         "cloud": 55,
#                         "feelslike_c": 16.5,
#                         "feelslike_f": 61.6,
#                         "windchill_c": 16.5,
#                         "windchill_f": 61.6,
#                         "heatindex_c": 16.5,
#                         "heatindex_f": 61.7,
#                         "dewpoint_c": 13.8,
#                         "dewpoint_f": 56.9,
#                         "will_it_rain": 0,
#                         "chance_of_rain": 0,
#                         "will_it_snow": 0,
#                         "chance_of_snow": 0,
#                         "vis_km": 10.0,
#                         "vis_miles": 6.0,
#                         "gust_mph": 8.4,
#                         "gust_kph": 13.5,
#                         "uv": 0,
#                         "short_rad": 0,
#                         "diff_rad": 0,
#                         "dni": 0,
#                         "gti": 0,
#                     },
#                     {
#                         "time_epoch": 1757073600,
#                         "time": "2025-09-05 05:00",
#                         "temp_c": 16.2,
#                         "temp_f": 61.1,
#                         "is_day": 0,
#                         "condition": {
#                             "text": "Partly Cloudy ",
#                             "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
#                             "code": 1003,
#                         },
#                         "wind_mph": 4.5,
#                         "wind_kph": 7.2,
#                         "wind_degree": 162,
#                         "wind_dir": "SSE",
#                         "pressure_mb": 1010.0,
#                         "pressure_in": 29.83,
#                         "precip_mm": 0.0,
#                         "precip_in": 0.0,
#                         "snow_cm": 0.0,
#                         "humidity": 87,
#                         "cloud": 57,
#                         "feelslike_c": 16.2,
#                         "feelslike_f": 61.1,
#                         "windchill_c": 16.2,
#                         "windchill_f": 61.1,
#                         "heatindex_c": 16.2,
#                         "heatindex_f": 61.1,
#                         "dewpoint_c": 13.9,
#                         "dewpoint_f": 57.0,
#                         "will_it_rain": 0,
#                         "chance_of_rain": 0,
#                         "will_it_snow": 0,
#                         "chance_of_snow": 0,
#                         "vis_km": 10.0,
#                         "vis_miles": 6.0,
#                         "gust_mph": 8.3,
#                         "gust_kph": 13.3,
#                         "uv": 0,
#                         "short_rad": 0,
#                         "diff_rad": 0,
#                         "dni": 0,
#                         "gti": 0,
#                     },
#                     {
#                         "time_epoch": 1757077200,
#                         "time": "2025-09-05 06:00",
#                         "temp_c": 16.0,
#                         "temp_f": 60.8,
#                         "is_day": 0,
#                         "condition": {
#                             "text": "Cloudy ",
#                             "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
#                             "code": 1006,
#                         },
#                         "wind_mph": 4.0,
#                         "wind_kph": 6.5,
#                         "wind_degree": 155,
#                         "wind_dir": "SSE",
#                         "pressure_mb": 1011.0,
#                         "pressure_in": 29.84,
#                         "precip_mm": 0.0,
#                         "precip_in": 0.0,
#                         "snow_cm": 0.0,
#                         "humidity": 88,
#                         "cloud": 65,
#                         "feelslike_c": 16.0,
#                         "feelslike_f": 60.8,
#                         "windchill_c": 16.0,
#                         "windchill_f": 60.8,
#                         "heatindex_c": 16.0,
#                         "heatindex_f": 60.8,
#                         "dewpoint_c": 13.9,
#                         "dewpoint_f": 57.1,
#                         "will_it_rain": 0,
#                         "chance_of_rain": 0,
#                         "will_it_snow": 0,
#                         "chance_of_snow": 0,
#                         "vis_km": 10.0,
#                         "vis_miles": 6.0,
#                         "gust_mph": 7.3,
#                         "gust_kph": 11.8,
#                         "uv": 0,
#                         "short_rad": 0,
#                         "diff_rad": 0,
#                         "dni": 0,
#                         "gti": 0,
#                     },
#                     {
#                         "time_epoch": 1757080800,
#                         "time": "2025-09-05 07:00",
#                         "temp_c": 16.4,
#                         "temp_f": 61.6,
#                         "is_day": 1,
#                         "condition": {
#                             "text": "Cloudy ",
#                             "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
#                             "code": 1006,
#                         },
#                         "wind_mph": 3.8,
#                         "wind_kph": 6.1,
#                         "wind_degree": 145,
#                         "wind_dir": "SE",
#                         "pressure_mb": 1011.0,
#                         "pressure_in": 29.85,
#                         "precip_mm": 0.0,
#                         "precip_in": 0.0,
#                         "snow_cm": 0.0,
#                         "humidity": 89,
#                         "cloud": 65,
#                         "feelslike_c": 16.4,
#                         "feelslike_f": 61.6,
#                         "windchill_c": 16.4,
#                         "windchill_f": 61.6,
#                         "heatindex_c": 16.4,
#                         "heatindex_f": 61.6,
#                         "dewpoint_c": 13.9,
#                         "dewpoint_f": 57.1,
#                         "will_it_rain": 0,
#                         "chance_of_rain": 0,
#                         "will_it_snow": 0,
#                         "chance_of_snow": 0,
#                         "vis_km": 10.0,
#                         "vis_miles": 6.0,
#                         "gust_mph": 6.8,
#                         "gust_kph": 10.9,
#                         "uv": 0.0,
#                         "short_rad": 1.78,
#                         "diff_rad": 0.86,
#                         "dni": 1.11,
#                         "gti": 1.17,
#                     },
#                     {
#                         "time_epoch": 1757084400,
#                         "time": "2025-09-05 08:00",
#                         "temp_c": 17.6,
#                         "temp_f": 63.6,
#                         "is_day": 1,
#                         "condition": {
#                             "text": "Sunny",
#                             "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
#                             "code": 1000,
#                         },
#                         "wind_mph": 3.8,
#                         "wind_kph": 6.1,
#                         "wind_degree": 164,
#                         "wind_dir": "SSE",
#                         "pressure_mb": 1011.0,
#                         "pressure_in": 29.85,
#                         "precip_mm": 0.0,
#                         "precip_in": 0.0,
#                         "snow_cm": 0.0,
#                         "humidity": 79,
#                         "cloud": 9,
#                         "feelslike_c": 17.6,
#                         "feelslike_f": 63.6,
#                         "windchill_c": 17.6,
#                         "windchill_f": 63.6,
#                         "heatindex_c": 17.6,
#                         "heatindex_f": 63.6,
#                         "dewpoint_c": 13.3,
#                         "dewpoint_f": 56.0,
#                         "will_it_rain": 0,
#                         "chance_of_rain": 0,
#                         "will_it_snow": 0,
#                         "chance_of_snow": 0,
#                         "vis_km": 10.0,
#                         "vis_miles": 6.0,
#                         "gust_mph": 4.7,
#                         "gust_kph": 7.6,
#                         "uv": 0.5,
#                         "short_rad": 39.04,
#                         "diff_rad": 12.19,
#                         "dni": 35.87,
#                         "gti": 22.52,
#                     },
#                     {
#                         "time_epoch": 1757088000,
#                         "time": "2025-09-05 09:00",
#                         "temp_c": 19.2,
#                         "temp_f": 66.6,
#                         "is_day": 1,
#                         "condition": {
#                             "text": "Sunny",
#                             "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
#                             "code": 1000,
#                         },
#                         "wind_mph": 4.0,
#                         "wind_kph": 6.5,
#                         "wind_degree": 186,
#                         "wind_dir": "S",
#                         "pressure_mb": 1011.0,
#                         "pressure_in": 29.85,
#                         "precip_mm": 0.0,
#                         "precip_in": 0.0,
#                         "snow_cm": 0.0,
#                         "humidity": 72,
#                         "cloud": 9,
#                         "feelslike_c": 19.2,
#                         "feelslike_f": 66.6,
#                         "windchill_c": 19.2,
#                         "windchill_f": 66.6,
#                         "heatindex_c": 19.2,
#                         "heatindex_f": 66.6,
#                         "dewpoint_c": 13.5,
#                         "dewpoint_f": 56.3,
#                         "will_it_rain": 0,
#                         "chance_of_rain": 0,
#                         "will_it_snow": 0,
#                         "chance_of_snow": 0,
#                         "vis_km": 10.0,
#                         "vis_miles": 6.0,
#                         "gust_mph": 4.6,
#                         "gust_kph": 7.5,
#                         "uv": 1.5,
#                         "short_rad": 108.0,
#                         "diff_rad": 23.75,
#                         "dni": 134.26,
#                         "gti": 59.39,
#                     },
#                     {
#                         "time_epoch": 1757091600,
#                         "time": "2025-09-05 10:00",
#                         "temp_c": 21.5,
#                         "temp_f": 70.6,
#                         "is_day": 1,
#                         "condition": {
#                             "text": "Sunny",
#                             "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
#                             "code": 1000,
#                         },
#                         "wind_mph": 4.5,
#                         "wind_kph": 7.2,
#                         "wind_degree": 211,
#                         "wind_dir": "SSW",
#                         "pressure_mb": 1011.0,
#                         "pressure_in": 29.85,
#                         "precip_mm": 0.0,
#                         "precip_in": 0.0,
#                         "snow_cm": 0.0,
#                         "humidity": 63,
#                         "cloud": 0,
#                         "feelslike_c": 21.5,
#                         "feelslike_f": 70.6,
#                         "windchill_c": 21.5,
#                         "windchill_f": 70.6,
#                         "heatindex_c": 22.2,
#                         "heatindex_f": 72.0,
#                         "dewpoint_c": 13.7,
#                         "dewpoint_f": 56.6,
#                         "will_it_rain": 0,
#                         "chance_of_rain": 0,
#                         "will_it_snow": 0,
#                         "chance_of_snow": 0,
#                         "vis_km": 10.0,
#                         "vis_miles": 6.0,
#                         "gust_mph": 5.1,
#                         "gust_kph": 8.3,
#                         "uv": 3.3,
#                         "short_rad": 188.77,
#                         "diff_rad": 32.99,
#                         "dni": 332.54,
#                         "gti": 107.46,
#                     },
#                     {
#                         "time_epoch": 1757095200,
#                         "time": "2025-09-05 11:00",
#                         "temp_c": 25.1,
#                         "temp_f": 77.2,
#                         "is_day": 1,
#                         "condition": {
#                             "text": "Sunny",
#                             "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
#                             "code": 1000,
#                         },
#                         "wind_mph": 4.5,
#                         "wind_kph": 7.2,
#                         "wind_degree": 221,
#                         "wind_dir": "SW",
#                         "pressure_mb": 1010.0,
#                         "pressure_in": 29.83,
#                         "precip_mm": 0.0,
#                         "precip_in": 0.0,
#                         "snow_cm": 0.0,
#                         "humidity": 56,
#                         "cloud": 0,
#                         "feelslike_c": 25.8,
#                         "feelslike_f": 78.4,
#                         "windchill_c": 25.1,
#                         "windchill_f": 77.2,
#                         "heatindex_c": 25.8,
#                         "heatindex_f": 78.4,
#                         "dewpoint_c": 14.3,
#                         "dewpoint_f": 57.8,
#                         "will_it_rain": 0,
#                         "chance_of_rain": 0,
#                         "will_it_snow": 0,
#                         "chance_of_snow": 0,
#                         "vis_km": 10.0,
#                         "vis_miles": 6.0,
#                         "gust_mph": 5.1,
#                         "gust_kph": 8.3,
#                         "uv": 5.3,
#                         "short_rad": 270.43,
#                         "diff_rad": 40.28,
#                         "dni": 815.23,
#                         "gti": 180.36,
#                     },
#                     {
#                         "time_epoch": 1757098800,
#                         "time": "2025-09-05 12:00",
#                         "temp_c": 28.1,
#                         "temp_f": 82.6,
#                         "is_day": 1,
#                         "condition": {
#                             "text": "Sunny",
#                             "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
#                             "code": 1000,
#                         },
#                         "wind_mph": 4.9,
#                         "wind_kph": 7.9,
#                         "wind_degree": 224,
#                         "wind_dir": "SW",
#                         "pressure_mb": 1010.0,
#                         "pressure_in": 29.82,
#                         "precip_mm": 0.0,
#                         "precip_in": 0.0,
#                         "snow_cm": 0.0,
#                         "humidity": 48,
#                         "cloud": 0,
#                         "feelslike_c": 28.8,
#                         "feelslike_f": 83.8,
#                         "windchill_c": 28.1,
#                         "windchill_f": 82.6,
#                         "heatindex_c": 28.8,
#                         "heatindex_f": 83.8,
#                         "dewpoint_c": 16.5,
#                         "dewpoint_f": 61.8,
#                         "will_it_rain": 0,
#                         "chance_of_rain": 0,
#                         "will_it_snow": 0,
#                         "chance_of_snow": 0,
#                         "vis_km": 10.0,
#                         "vis_miles": 6.0,
#                         "gust_mph": 5.7,
#                         "gust_kph": 9.1,
#                         "uv": 6.9,
#                         "short_rad": 800.02,
#                         "diff_rad": 80.24,
#                         "dni": 8804.22,
#                         "gti": 1088.58,
#                     },
#                     {
#                         "time_epoch": 1757102400,
#                         "time": "2025-09-05 13:00",
#                         "temp_c": 29.4,
#                         "temp_f": 84.9,
#                         "is_day": 1,
#                         "condition": {
#                             "text": "Sunny",
#                             "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
#                             "code": 1000,
#                         },
#                         "wind_mph": 5.4,
#                         "wind_kph": 8.6,
#                         "wind_degree": 224,
#                         "wind_dir": "SW",
#                         "pressure_mb": 1009.0,
#                         "pressure_in": 29.8,
#                         "precip_mm": 0.0,
#                         "precip_in": 0.0,
#                         "snow_cm": 0.0,
#                         "humidity": 41,
#                         "cloud": 0,
#                         "feelslike_c": 29.6,
#                         "feelslike_f": 85.3,
#                         "windchill_c": 29.4,
#                         "windchill_f": 84.9,
#                         "heatindex_c": 29.6,
#                         "heatindex_f": 85.3,
#                         "dewpoint_c": 16.4,
#                         "dewpoint_f": 61.6,
#                         "will_it_rain": 0,
#                         "chance_of_rain": 0,
#                         "will_it_snow": 0,
#                         "chance_of_snow": 0,
#                         "vis_km": 10.0,
#                         "vis_miles": 6.0,
#                         "gust_mph": 6.2,
#                         "gust_kph": 9.9,
#                         "uv": 7.5,
#                         "short_rad": 832.7,
#                         "diff_rad": 80.79,
#                         "dni": 0.0,
#                         "gti": 90.2,
#                     },
#                     {
#                         "time_epoch": 1757106000,
#                         "time": "2025-09-05 14:00",
#                         "temp_c": 30.3,
#                         "temp_f": 86.6,
#                         "is_day": 1,
#                         "condition": {
#                             "text": "Partly Cloudy ",
#                             "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
#                             "code": 1003,
#                         },
#                         "wind_mph": 6.3,
#                         "wind_kph": 10.1,
#                         "wind_degree": 226,
#                         "wind_dir": "SW",
#                         "pressure_mb": 1009.0,
#                         "pressure_in": 29.79,
#                         "precip_mm": 0.0,
#                         "precip_in": 0.0,
#                         "snow_cm": 0.0,
#                         "humidity": 36,
#                         "cloud": 29,
#                         "feelslike_c": 30.2,
#                         "feelslike_f": 86.4,
#                         "windchill_c": 30.3,
#                         "windchill_f": 86.6,
#                         "heatindex_c": 30.2,
#                         "heatindex_f": 86.4,
#                         "dewpoint_c": 14.0,
#                         "dewpoint_f": 57.2,
#                         "will_it_rain": 0,
#                         "chance_of_rain": 0,
#                         "will_it_snow": 0,
#                         "chance_of_snow": 0,
#                         "vis_km": 10.0,
#                         "vis_miles": 6.0,
#                         "gust_mph": 7.2,
#                         "gust_kph": 11.6,
#                         "uv": 6.9,
#                         "short_rad": 844.88,
#                         "diff_rad": 80.74,
#                         "dni": 0.0,
#                         "gti": 90.42,
#                     },
#                     {
#                         "time_epoch": 1757109600,
#                         "time": "2025-09-05 15:00",
#                         "temp_c": 32.2,
#                         "temp_f": 89.9,
#                         "is_day": 1,
#                         "condition": {
#                             "text": "Cloudy ",
#                             "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
#                             "code": 1006,
#                         },
#                         "wind_mph": 6.5,
#                         "wind_kph": 10.4,
#                         "wind_degree": 227,
#                         "wind_dir": "SW",
#                         "pressure_mb": 1008.0,
#                         "pressure_in": 29.76,
#                         "precip_mm": 0.0,
#                         "precip_in": 0.0,
#                         "snow_cm": 0.0,
#                         "humidity": 33,
#                         "cloud": 85,
#                         "feelslike_c": 32.1,
#                         "feelslike_f": 89.8,
#                         "windchill_c": 32.2,
#                         "windchill_f": 89.9,
#                         "heatindex_c": 32.1,
#                         "heatindex_f": 89.8,
#                         "dewpoint_c": 13.1,
#                         "dewpoint_f": 55.5,
#                         "will_it_rain": 0,
#                         "chance_of_rain": 0,
#                         "will_it_snow": 0,
#                         "chance_of_snow": 0,
#                         "vis_km": 10.0,
#                         "vis_miles": 6.0,
#                         "gust_mph": 7.5,
#                         "gust_kph": 12.0,
#                         "uv": 5.3,
#                         "short_rad": 832.02,
#                         "diff_rad": 94.38,
#                         "dni": 0.0,
#                         "gti": 102.28,
#                     },
#                     {
#                         "time_epoch": 1757113200,
#                         "time": "2025-09-05 16:00",
#                         "temp_c": 32.8,
#                         "temp_f": 91.0,
#                         "is_day": 1,
#                         "condition": {
#                             "text": "Sunny",
#                             "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
#                             "code": 1000,
#                         },
#                         "wind_mph": 6.7,
#                         "wind_kph": 10.8,
#                         "wind_degree": 225,
#                         "wind_dir": "SW",
#                         "pressure_mb": 1007.0,
#                         "pressure_in": 29.74,
#                         "precip_mm": 0.0,
#                         "precip_in": 0.0,
#                         "snow_cm": 0.0,
#                         "humidity": 31,
#                         "cloud": 2,
#                         "feelslike_c": 32.6,
#                         "feelslike_f": 90.7,
#                         "windchill_c": 32.8,
#                         "windchill_f": 91.0,
#                         "heatindex_c": 32.6,
#                         "heatindex_f": 90.7,
#                         "dewpoint_c": 14.5,
#                         "dewpoint_f": 58.1,
#                         "will_it_rain": 0,
#                         "chance_of_rain": 0,
#                         "will_it_snow": 0,
#                         "chance_of_snow": 0,
#                         "vis_km": 10.0,
#                         "vis_miles": 6.0,
#                         "gust_mph": 7.7,
#                         "gust_kph": 12.4,
#                         "uv": 3.3,
#                         "short_rad": 797.23,
#                         "diff_rad": 110.3,
#                         "dni": 0.0,
#                         "gti": 115.69,
#                     },
#                     {
#                         "time_epoch": 1757116800,
#                         "time": "2025-09-05 17:00",
#                         "temp_c": 30.2,
#                         "temp_f": 86.4,
#                         "is_day": 1,
#                         "condition": {
#                             "text": "Sunny",
#                             "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
#                             "code": 1000,
#                         },
#                         "wind_mph": 6.9,
#                         "wind_kph": 11.2,
#                         "wind_degree": 215,
#                         "wind_dir": "SW",
#                         "pressure_mb": 1008.0,
#                         "pressure_in": 29.76,
#                         "precip_mm": 0.0,
#                         "precip_in": 0.0,
#                         "snow_cm": 0.0,
#                         "humidity": 33,
#                         "cloud": 0,
#                         "feelslike_c": 32.0,
#                         "feelslike_f": 89.7,
#                         "windchill_c": 32.3,
#                         "windchill_f": 90.2,
#                         "heatindex_c": 32.0,
#                         "heatindex_f": 89.7,
#                         "dewpoint_c": 13.8,
#                         "dewpoint_f": 56.8,
#                         "will_it_rain": 0,
#                         "chance_of_rain": 0,
#                         "will_it_snow": 0,
#                         "chance_of_snow": 0,
#                         "vis_km": 16.0,
#                         "vis_miles": 9.0,
#                         "gust_mph": 8.0,
#                         "gust_kph": 12.9,
#                         "uv": 1.7,
#                         "short_rad": 749.73,
#                         "diff_rad": 110.95,
#                         "dni": 0.0,
#                         "gti": 115.23,
#                     },
#                     {
#                         "time_epoch": 1757120400,
#                         "time": "2025-09-05 18:00",
#                         "temp_c": 30.7,
#                         "temp_f": 87.3,
#                         "is_day": 1,
#                         "condition": {
#                             "text": "Sunny",
#                             "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
#                             "code": 1000,
#                         },
#                         "wind_mph": 7.8,
#                         "wind_kph": 12.6,
#                         "wind_degree": 212,
#                         "wind_dir": "SSW",
#                         "pressure_mb": 1007.0,
#                         "pressure_in": 29.74,
#                         "precip_mm": 0.0,
#                         "precip_in": 0.0,
#                         "snow_cm": 0.0,
#                         "humidity": 32,
#                         "cloud": 0,
#                         "feelslike_c": 30.4,
#                         "feelslike_f": 86.8,
#                         "windchill_c": 30.7,
#                         "windchill_f": 87.3,
#                         "heatindex_c": 30.4,
#                         "heatindex_f": 86.8,
#                         "dewpoint_c": 13.3,
#                         "dewpoint_f": 56.0,
#                         "will_it_rain": 0,
#                         "chance_of_rain": 0,
#                         "will_it_snow": 0,
#                         "chance_of_snow": 0,
#                         "vis_km": 10.0,
#                         "vis_miles": 6.0,
#                         "gust_mph": 9.0,
#                         "gust_kph": 14.5,
#                         "uv": 0.6,
#                         "short_rad": 336.56,
#                         "diff_rad": 55.89,
#                         "dni": 0.0,
#                         "gti": 57.14,
#                     },
#                     {
#                         "time_epoch": 1757124000,
#                         "time": "2025-09-05 19:00",
#                         "temp_c": 28.2,
#                         "temp_f": 82.7,
#                         "is_day": 1,
#                         "condition": {
#                             "text": "Sunny",
#                             "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
#                             "code": 1000,
#                         },
#                         "wind_mph": 8.3,
#                         "wind_kph": 13.3,
#                         "wind_degree": 205,
#                         "wind_dir": "SSW",
#                         "pressure_mb": 1008.0,
#                         "pressure_in": 29.75,
#                         "precip_mm": 0.0,
#                         "precip_in": 0.0,
#                         "snow_cm": 0.0,
#                         "humidity": 38,
#                         "cloud": 0,
#                         "feelslike_c": 28.3,
#                         "feelslike_f": 82.9,
#                         "windchill_c": 28.2,
#                         "windchill_f": 82.7,
#                         "heatindex_c": 28.3,
#                         "heatindex_f": 82.9,
#                         "dewpoint_c": 13.3,
#                         "dewpoint_f": 55.9,
#                         "will_it_rain": 0,
#                         "chance_of_rain": 0,
#                         "will_it_snow": 0,
#                         "chance_of_snow": 0,
#                         "vis_km": 10.0,
#                         "vis_miles": 6.0,
#                         "gust_mph": 11.5,
#                         "gust_kph": 18.6,
#                         "uv": 0.0,
#                         "short_rad": 234.92,
#                         "diff_rad": 45.76,
#                         "dni": 0.0,
#                         "gti": 45.89,
#                     },
#                     {
#                         "time_epoch": 1757127600,
#                         "time": "2025-09-05 20:00",
#                         "temp_c": 25.5,
#                         "temp_f": 77.9,
#                         "is_day": 0,
#                         "condition": {
#                             "text": "Clear ",
#                             "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
#                             "code": 1000,
#                         },
#                         "wind_mph": 7.4,
#                         "wind_kph": 11.9,
#                         "wind_degree": 192,
#                         "wind_dir": "SSW",
#                         "pressure_mb": 1008.0,
#                         "pressure_in": 29.77,
#                         "precip_mm": 0.0,
#                         "precip_in": 0.0,
#                         "snow_cm": 0.0,
#                         "humidity": 47,
#                         "cloud": 0,
#                         "feelslike_c": 26.5,
#                         "feelslike_f": 79.8,
#                         "windchill_c": 25.5,
#                         "windchill_f": 77.9,
#                         "heatindex_c": 26.5,
#                         "heatindex_f": 79.8,
#                         "dewpoint_c": 13.4,
#                         "dewpoint_f": 56.1,
#                         "will_it_rain": 0,
#                         "chance_of_rain": 0,
#                         "will_it_snow": 0,
#                         "chance_of_snow": 0,
#                         "vis_km": 10.0,
#                         "vis_miles": 6.0,
#                         "gust_mph": 13.0,
#                         "gust_kph": 20.9,
#                         "uv": 0,
#                         "short_rad": 0,
#                         "diff_rad": 0,
#                         "dni": 0,
#                         "gti": 0,
#                     },
#                     {
#                         "time_epoch": 1757131200,
#                         "time": "2025-09-05 21:00",
#                         "temp_c": 23.1,
#                         "temp_f": 73.6,
#                         "is_day": 0,
#                         "condition": {
#                             "text": "Clear ",
#                             "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
#                             "code": 1000,
#                         },
#                         "wind_mph": 6.5,
#                         "wind_kph": 10.4,
#                         "wind_degree": 172,
#                         "wind_dir": "S",
#                         "pressure_mb": 1009.0,
#                         "pressure_in": 29.8,
#                         "precip_mm": 0.0,
#                         "precip_in": 0.0,
#                         "snow_cm": 0.0,
#                         "humidity": 57,
#                         "cloud": 0,
#                         "feelslike_c": 23.6,
#                         "feelslike_f": 74.5,
#                         "windchill_c": 23.1,
#                         "windchill_f": 73.6,
#                         "heatindex_c": 23.6,
#                         "heatindex_f": 74.5,
#                         "dewpoint_c": 13.8,
#                         "dewpoint_f": 56.8,
#                         "will_it_rain": 0,
#                         "chance_of_rain": 0,
#                         "will_it_snow": 0,
#                         "chance_of_snow": 0,
#                         "vis_km": 10.0,
#                         "vis_miles": 6.0,
#                         "gust_mph": 11.5,
#                         "gust_kph": 18.4,
#                         "uv": 0,
#                         "short_rad": 0,
#                         "diff_rad": 0,
#                         "dni": 0,
#                         "gti": 0,
#                     },
#                     {
#                         "time_epoch": 1757134800,
#                         "time": "2025-09-05 22:00",
#                         "temp_c": 21.1,
#                         "temp_f": 70.1,
#                         "is_day": 0,
#                         "condition": {
#                             "text": "Clear ",
#                             "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
#                             "code": 1000,
#                         },
#                         "wind_mph": 6.5,
#                         "wind_kph": 10.4,
#                         "wind_degree": 152,
#                         "wind_dir": "SSE",
#                         "pressure_mb": 1010.0,
#                         "pressure_in": 29.82,
#                         "precip_mm": 0.0,
#                         "precip_in": 0.0,
#                         "snow_cm": 0.0,
#                         "humidity": 65,
#                         "cloud": 0,
#                         "feelslike_c": 21.1,
#                         "feelslike_f": 70.1,
#                         "windchill_c": 21.1,
#                         "windchill_f": 70.1,
#                         "heatindex_c": 21.4,
#                         "heatindex_f": 70.5,
#                         "dewpoint_c": 13.9,
#                         "dewpoint_f": 57.0,
#                         "will_it_rain": 0,
#                         "chance_of_rain": 0,
#                         "will_it_snow": 0,
#                         "chance_of_snow": 0,
#                         "vis_km": 10.0,
#                         "vis_miles": 6.0,
#                         "gust_mph": 11.5,
#                         "gust_kph": 18.5,
#                         "uv": 0,
#                         "short_rad": 0,
#                         "diff_rad": 0,
#                         "dni": 0,
#                         "gti": 0,
#                     },
#                     {
#                         "time_epoch": 1757138400,
#                         "time": "2025-09-05 23:00",
#                         "temp_c": 19.5,
#                         "temp_f": 67.1,
#                         "is_day": 0,
#                         "condition": {
#                             "text": "Clear ",
#                             "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
#                             "code": 1000,
#                         },
#                         "wind_mph": 6.3,
#                         "wind_kph": 10.1,
#                         "wind_degree": 147,
#                         "wind_dir": "SSE",
#                         "pressure_mb": 1010.0,
#                         "pressure_in": 29.83,
#                         "precip_mm": 0.0,
#                         "precip_in": 0.0,
#                         "snow_cm": 0.0,
#                         "humidity": 71,
#                         "cloud": 0,
#                         "feelslike_c": 19.5,
#                         "feelslike_f": 67.1,
#                         "windchill_c": 19.5,
#                         "windchill_f": 67.1,
#                         "heatindex_c": 19.6,
#                         "heatindex_f": 67.3,
#                         "dewpoint_c": 13.9,
#                         "dewpoint_f": 57.0,
#                         "will_it_rain": 0,
#                         "chance_of_rain": 0,
#                         "will_it_snow": 0,
#                         "chance_of_snow": 0,
#                         "vis_km": 10.0,
#                         "vis_miles": 6.0,
#                         "gust_mph": 11.3,
#                         "gust_kph": 18.3,
#                         "uv": 0,
#                         "short_rad": 0,
#                         "diff_rad": 0,
#                         "dni": 0,
#                         "gti": 0,
#                     },
#                 ],
#             }
#         ]
#     },
# }
